#' Sample-level gene counts of young and old mice
#'
#' A sparse Matrix containing the sample-level gene counts of young (3 months)
#' and old (24 months) mice. Generated by using scagg
#' @format A sparse Matrix with 25 rows and 15 variables:
#' \describe{
#'   \item{o1-o7}{sample IDs for old mice}
#'   \item{y1-y8}{sample IDs for young mice}
#' }
"agg_counts"
