#' Returns plot objects and generates visualisation
#'
#' This function generates various plots as objects that you can choose how to
#' visualise. Optionally, all visualisation can also be set to a single PDF
#' file.
#' @param dds DESeqDataSet object with results generated by running DE analysis
#' on a DESeqDataSet object
#' @param comparison A string in form 'condition,group A,group B'
#' @param do_write Output is written to file
#' @examples
#' # Rasic run
#' example_out <- scout(dds = agg_dds, comparison = "state,young,old",
#'                      do_write = FALSE)
#' @return Optionally returns the data frame otherwise sent to xlsx file
#' @export
schow <- function(dds,
                  comparison = "state,young,old",
                  do_write = FALSE,
                  do_rlog = FALSE) {

  # Define variables ---------------------------
  spl_com <- strsplit(comparison, split = ",")[[1]]
  res <- DESeq2::lfcShrink(dds, contrast = spl_com, type = "ashr", quiet = TRUE)
  rpval <- res$pvalue
  rpadj <- res$padj
  rl2fc <- res$log2FoldChange
  rcols <- densCols(rl2fc, -log10(rpval))
  rsc_g <- abs(rl2fc) > 2.5 & rpadj < 0.05

  # Transform data ---------------------------
  if (do_rlog) {
    rld <- DESeq2::rlog(dds, blind = FALSE)
    rlb <- DESeq2::rlog(dds)
  } else {
    rld <- NULL
    rlb <- NULL
  }
  vsd <- DESeq2::varianceStabilizingTransformation(dds, blind = FALSE)
  vsb <- DESeq2::varianceStabilizingTransformation(dds)

  trans_list <- list(rlog = rld,
                     rlog_b = rlb,
                     varstab = vsd,
                     varstab_b = vsb)

  trans_list <- trans_list[!sapply(trans_list, is.null)]

  # Get PCA values ---------------------------
  pca_list <- lapply(trans_list, DESeq2::plotPCA, intgroup = spl_com[1], returnData = TRUE)

  # Get MA values ---------------------------
  ma_list <- list(res_MA = DESeq2::plotMA(res, returnData = TRUE))

  # Get volcano values ---------------------------

  # (Opt) plot graphs ---------------------------
  if (do_write) {

    pdf("quality_metrics.pdf", width = 10, height = 10)

    lapply(names(pca_list), function(x) {
      pca_table <- pca_list[[x]]
      percentVar <- round(100 * attr(pca_table, "percentVar"))
      print(
        ggplot2::ggplot(pca_table, ggplot2::aes(PC1, PC2, colour = group)) +
        ggplot2::geom_point(size = 3) +
        ggrepel::geom_text_repel(ggplot2::aes(label = name)) +
        ggplot2::ggtitle(paste0("PCA plot for transformation: ", x)) +
        ggplot2::xlab(paste0("PC1: ", percentVar[1], "% variance")) +
        ggplot2::ylab(paste0("PC2: ", percentVar[2], "% variance")) +
        ggplot2::coord_fixed()
      )
    })

    DESeq2::plotMA(res, ylim = c(-4, 4), main = "Shrunken log2 Fold Change (ASHR)")


    # Plot genes to volcano
    plot(
      rl2fc,
      -log10(rpadj),
      col = rcols,
      panel.first = grid(),
      main = "Volcano plot",
      xlab = "Effect size: log2(fold-change)",
      ylab = "-log10(adjusted p-value)",
      pch = 20,
      cex = 0.6
    )
    abline(v = -1:1, h = -log10(0.05), col = c(rep("brown", 2), "black", "brown")
    )
    # Add text for sign. up/down regulated genes
    #if (sum(sc_g, na.rm = TRUE)) {
    #  text(
    #    x         = l2fc[sc_g],
    #    y         = -log10(padj)[sc_g],
    #    lab       = nm_g[sc_g],
    #    cex       = 0.4
    #  )


    dev.off()
  }

  all_list <- c(pca_list, ma_list)
  return(all_list)

}
