#' Returns plot objects and generates visualisation
#'
#' This function generates various plots as objects that you can choose how to
#' visualise. Optionally, all visualisation can also be set to a single PDF
#' file.
#' @param dds DESeqDataSet object with results generated by running DE analysis
#' on a DESeqDataSet object
#' @param comparison A string in form 'condition,group A,group B'
#' @param out_path Path to output directory (default is NULL)
#' @param do_write Output is written to PDF file
#' @param do_labels Output PCA plots will have labeled data points
#' @param do_rlog Indicate whether DESeq2 output is transformed using
#' regularized log
#' @param do_return Output is returned as list of objects
#' @examples
#' # Rasic run, generate quality_metrics.pdf
#' schow(
#'   dds = agg_dds, comparison = "state,young,old",
#'   out_path = "example/output/path"
#' )
#'
#' # return values as list, do not use rlog transform to speed up process
#' example_show <- schow(
#'   dds = agg_dds, comparison = "state,young,old",
#'   do_write = FALSE, do_rlog = FALSE, do_return = TRUE
#' )
#' @return Optionally returns output from calling DESeq2's plotPCA and plotMA
#' with returnData = TRUE
#' @export
schow <- function(dds,
                  comparison = "state,young,old",
                  out_path = NULL,
                  do_write = TRUE,
                  do_labels = TRUE,
                  do_rlog = TRUE,
                  do_return = FALSE) {
  # Test for any output ---------------------------
  if (!do_write & !do_return) {
    message("Neither writing nor assignment has be set.")
    message("Change either or both arguments do_write/do_return to TRUE.\n")
    message("Exiting function call...")
  } else {

    # Define variables ---------------------------
    spl_com <- strsplit(comparison, split = ",")[[1]]
    res <- DESeq2::lfcShrink(dds,
      contrast = spl_com, type = "ashr",
      quiet = TRUE
    )
    rpval <- res$pvalue
    rpadj <- res$padj
    rl2fc <- res$log2FoldChange
    rcols <- densCols(rl2fc, -log10(rpval))
    rsc_g <- abs(rl2fc) > 2.5 & rpadj < 0.05
    rnm_g <- rownames(res)[rsc_g]
    if (is.null(out_path)) {
      out_path <- "."
    }

    # Transform data ---------------------------
    if (do_rlog) {
      rld <- DESeq2::rlog(dds, blind = FALSE)
      rlb <- DESeq2::rlog(dds)
    } else {
      rld <- NULL
      rlb <- NULL
    }
    vsd <- DESeq2::varianceStabilizingTransformation(dds, blind = FALSE)
    vsb <- DESeq2::varianceStabilizingTransformation(dds)

    trans_list <- list(
      rlog = rld,
      rlog_b = rlb,
      varstab = vsd,
      varstab_b = vsb
    )

    trans_list <- trans_list[!sapply(trans_list, is.null)]

    # Get PCA values ---------------------------
    pca_list <- lapply(trans_list, DESeq2::plotPCA,
      intgroup = spl_com[1],
      returnData = TRUE
    )

    # Get MA values ---------------------------
    ma_list <- list(res_MA = DESeq2::plotMA(res, returnData = TRUE))

    # (Opt) plot graphs ---------------------------
    if (do_write) {
      pdf(paste0(out_path, "/quality_metrics.pdf"), width = 10, height = 7.2)

      for (i in names(pca_list)) {
        pca_table <- pca_list[[i]]
        percentVar <- round(100 * attr(pca_table, "percentVar"))

        plot(
          pca_table$PC1,
          pca_table$PC2,
          ylim = range(pca_table$PC2),
          xlim = range(pca_table$PC1),
          cex = 1.3,
          pch = 19,
          col = c("#66BD63", "#FDAE61")[pca_table$group],
          main = paste0("PCA plot for transformation: ", i),
          xlab = paste0("PC1: ", percentVar[1], "% variance"),
          ylab = paste0("PC2: ", percentVar[2], "% variance")
        )
        legend(
          "topright",
          inset = c(0.02, 0.02),
          legend = levels(pca_table$group),
          col = c("#66BD63", "#FDAE61"),
          pch = 19,
          cex = 0.8
        )
        if (do_labels) {
          text(pca_table$PC1, pca_table$PC2, labels = pca_table$name)
        }
      }

      DESeq2::plotMA(res, ylim = c(-4, 4), main = "Shrunken log2 Fold Change (ASHR)")

      plot(
        rl2fc,
        -log10(rpadj),
        col = rcols,
        panel.first = grid(),
        main = "Volcano plot",
        xlab = "Effect size: log2(fold-change)",
        ylab = "-log10(adjusted p-value)",
        pch = 20,
        cex = 0.6
      )
      abline(
        v = -1:1, h = -log10(0.05),
        col = c(rep("brown", 2), "black", "brown")
      )
      if (sum(rsc_g, na.rm = TRUE)) {
        text(
          x         = rl2fc[rsc_g],
          y         = -log10(rpadj)[rsc_g],
          lab       = rnm_g,
          cex       = 0.6
        )
      }

      dev.off()
    }

    if (do_return) {
      all_list <- c(pca_list, ma_list)
      return(all_list)
    }
  }
}
