#' Create a xlsx file from the 'DESeq2' results
#'
#' This function works as a helper for generating 'DESeq2' output. Output is
#' an xlsx file with the differentially expressed genes.
#' @param dds DESeqDataSet object with results generated by running DE analysis
#' on a DESeqDataSet object
#' @param comparison A string in form 'condition,group A,group B'
#' @param do_write Output is written to file
#' @examples
#' # Rasic run
#' example_out <- scout(
#'   dds = agg_dds, comparison = "state,young,old",
#'   do_write = FALSE
#' )
#' @return Optionally returns the data frame otherwise sent to xlsx file
#' @export
scout <- function(dds, comparison = "state,young,old", do_write = TRUE) {

  # Define variables
  spl_com <- strsplit(comparison, split = ",")[[1]]
  file_name <- paste0(spl_com[2], "V", spl_com[3])
  xlsx_name <- paste0(file_name, ".DESeq2.xlsx")
  xlsx_head <- openxlsx::createStyle(
    textDecoration = "BOLD",
    fgFill = "#4FBD61"
  )

  # Generate result table with ASHR-shrunk log2FC
  res <- data.frame(DESeq2::lfcShrink(dds,
    contrast = spl_com, type = "ashr",
    quiet = TRUE
  ))

  # Compute normalized counts
  norm_counts <- data.frame(DESeq2::counts(dds, normalized = TRUE))

  # Combine data.tables into ouput table
  out_res <- cbind(res, norm_counts)

  # Clarify column content
  colnames(out_res)[1:5] <- c(
    "basemean", "l2fc_ASHR", "standerror_ASHR",
    "pvalue", "padj"
  )

  # Reorder output table on adjusted p-value
  out_res <- out_res[order(out_res$padj), c(4:5, 2:3, 1, 6:ncol(out_res))]

  # Select significant genes
  out_sign <- stats::na.omit(out_res[out_res$padj < 0.05, ])

  if (do_write) {
    # Create summary file
    sink(file = paste0(file_name, ".summary.txt"))
    summary(res)
    sink()

    # Create workbook and set default border Colour and style
    wb <- openxlsx::createWorkbook()

    # Add Sheets
    openxlsx::addWorksheet(wb, sheetName = "padj<0.05 genes")
    openxlsx::addWorksheet(wb, sheetName = "padj<0.05 genes+counts")
    openxlsx::addWorksheet(wb, sheetName = "classic DESeq2 output")

    # Set widths and freeze first row/column
    for (i in 1:3) {
      openxlsx::freezePane(wb, sheet = i, firstRow = TRUE, firstCol = TRUE)
      openxlsx::setColWidths(wb, sheet = i, cols = "A", widths = 24)
    }

    # Write sign df genes to padj<0.05: genes
    openxlsx::writeDataTable(
      wb,
      sheet = 1,
      x = out_sign[, 1:6],
      rowNames = TRUE,
      headerStyle = xlsx_head
    )

    # Write sign df to padj<0.05: genes+counts
    openxlsx::writeDataTable(
      wb,
      sheet = 2,
      x = out_sign,
      rowNames = TRUE,
      headerStyle = xlsx_head
    )

    # Write output df to classic DESeq2 output
    openxlsx::writeDataTable(
      wb,
      sheet = 3,
      x = out_res,
      rowNames = TRUE,
      headerStyle = xlsx_head
    )

    # Save workbook
    openxlsx::saveWorkbook(wb, xlsx_name, overwrite = TRUE)
  }

  return(out_res)
}
