#' Create a xlsx file from the 'DESeq2' results
#'
#' This function works as a helper for generating 'DESeq2' output. Output is
#' an xlsx file with the differentially expressed genes.
#' @param dds DESeqDataSet object with results generated by running DE analysis
#' on a DESeqDataSet object
#' @param comparison A string in form 'condition,group A,group B'
#' @param out_path Path to output directory (default is NULL)
#' @param do_write Output is written to file
#' @param do_return Output is returned as data frame
#' @examples
#' # Examples given with all optional parameters for education purposes
#' \dontrun{
#' # Rasic run, generate DESeq2.xlsx
#' scout(
#'   dds = agg_dds,
#'   comparison = "state,young,old",
#'   out_path = "/example/output/path",
#'   do_write = TRUE,
#'   do_return = FALSE
#' )
#' }
#' # return values as data.frame
#' example_out <- scout(
#'   dds = agg_dds,
#'   comparison = "state,young,old",
#'   out_path = NULL,
#'   do_write = FALSE,
#'   do_return = TRUE
#' )
#' @return Optionally returns the data frame otherwise sent to xlsx file
#' @export
scout <- function(dds,
                  comparison = "state,young,old",
                  out_path = NULL,
                  do_write = TRUE,
                  do_return = FALSE) {

  # Test for any output ---------------------------
  if (!do_write & !do_return) {
    message("Neither writing nor assignment has been set.")
    message("Change either or both arguments do_write/do_return to TRUE.\n")
    message("Exiting function call...")
  } else {

    # Define variables ---------------------------
    spl_com <- strsplit(comparison, split = ",")[[1]]
    file_name <- paste0("/", spl_com[2], "V", spl_com[3])
    xlsx_name <- paste0(file_name, ".DESeq2.xlsx")
    xlsx_head <- openxlsx::createStyle(
      textDecoration = "BOLD",
      fgFill = "#4FBD61"
    )
    if (is.null(out_path)) {
      out_path <- "."
    }

    # Generate result with ASHR-shrunk log2FC ---------------------------
    res <- data.frame(DESeq2::lfcShrink(dds,
      contrast = spl_com, type = "ashr",
      quiet = TRUE
    ))

    # Compute normalized counts ---------------------------
    norm_counts <- data.frame(DESeq2::counts(dds, normalized = TRUE))

    # Combine and reconfigure results for output ---------------------------
    out_res <- cbind(res, norm_counts)
    colnames(out_res)[1:5] <- c(
      "basemean", "l2fc_ASHR", "standerror_ASHR",
      "pvalue", "padj"
    )
    out_res <- out_res[order(out_res$padj), c(4:5, 2:3, 1, 6:ncol(out_res))]

    # Select significant genes ---------------------------
    out_sign <- stats::na.omit(out_res[out_res$padj < 0.05, ])

    # Test for writing output ---------------------------
    if (do_write) {
      # Create summary file ---------------------------
      sink(file = paste0(out_path, file_name, ".summary.txt"))
      summary(res)
      sink()

      # Create XLSX file ---------------------------
      wb <- openxlsx::createWorkbook()

      openxlsx::addWorksheet(wb, sheetName = "padj<0.05 genes")
      openxlsx::addWorksheet(wb, sheetName = "padj<0.05 genes+counts")
      openxlsx::addWorksheet(wb, sheetName = "classic DESeq2 output")

      for (i in 1:3) {
        openxlsx::freezePane(wb, sheet = i, firstRow = TRUE, firstCol = TRUE)
        openxlsx::setColWidths(wb, sheet = i, cols = "A", widths = 24)
      }

      openxlsx::writeDataTable(
        wb,
        sheet = 1,
        x = out_sign[, 1:6],
        rowNames = TRUE,
        headerStyle = xlsx_head
      )

      openxlsx::writeDataTable(
        wb,
        sheet = 2,
        x = out_sign,
        rowNames = TRUE,
        headerStyle = xlsx_head
      )

      openxlsx::writeDataTable(
        wb,
        sheet = 3,
        x = out_res,
        rowNames = TRUE,
        headerStyle = xlsx_head
      )

      # Save workbook ---------------------------
      openxlsx::saveWorkbook(wb, paste0(out_path, xlsx_name), overwrite = TRUE)
    }

    # Test for assigning output ---------------------------
    if (do_return) {
      return(out_res)
    }
  }
}
