#' Create a xlsx file from the DESeq2 results
#'
#' This function works as a helper for generating DESeq2 output. User can choose
#' whether to remove genes with low overall counts in the samples. Output exists
#' out of a xlsx file with the differentially expressed genes.
#' @param dds DESeqDataSet object generated by callingList generated by the run_pseudobulkDE function.
#' @param contrasts A string in form 'condition,group A,group B'.
#' @examples
# Set annotation table to data.table
setDT(agg_table)

# Define columns for annotation table
if (class(agg_cell) == "character") {
  annot_col <- colnames(agg_table)[colnames(agg_table) != agg_cell]
} else {
  annot_col <- colnames(agg_table)[-agg_cell]
}

# Create annotation table
annot_table <- unique(agg_table[order(agg_group), annot_col, with = FALSE])


annot_counts <- t.Mat(agg.Mat(t.Mat(sc_counts), groupings = agg_table[, agg_group]))
return(list(counts = annot_counts, annot = annot_table))
